

GROUP_CAREERS = {
    "E": [
        "Advertising Account Executive",
        "Advertising Copywriter",
        "Advertising Manager",
        "Advertising Sales Representative",
        "Automobile Salesperson",
        "Bakery Manager",
        "Bank Cashier",
        "Commercial Broker",
        "Customer-Service Representative/Call Center Agent",
        "Farm Manager",
        "Front-Office Hotel Manager",
        "High-School Principal",
        "Hotel Manager",
        "Insurance Agent",
        "Jeweler",
        "Pawnbroker",
        "Public Relations Representative",
        "Real Estate Agent",
        "Sales Manager",
        "Stockbroker",
        "Wholesaler",
    ],
    "CE": [
        "Bank Cashier",
        "Bus-Station Manager",
        "Executive Secretary",
        "Fire Inspector",
        "Hotel Bell Captain",
        "Legal Assistant",
        "Pawnbroker",
        "Postmaster",
        "Secretary",
        "Travel Agent",
        "Warehouse Manager",
    ],
    "CLE": [
        "Accountant",
        "Book Editor",
        "Certified Public Accountant",
        "Executive Secretary",
        "Head Nurse",
        "Librarian",
    ],
    "CEM": [
        "Building Inspector",
        "Certified Public Accountant",
        "Fire Inspector",
    ],
    "NCE": [
        "Accountant",
        "Accounting Clerk",
        "Auditor",
        "Bank Cashier",
        "Economist",
        "Real Estate Agent",
    ],
    "CIE": [
        "Advertising Copywriter",
        "Airline-Lounge Receptionist",
        "Executive Secretary",
        "Head Nurse",
        "Legal Assistant",
        "Reception Clerk",
        "Secondary-School Teacher",
    ],
    "LE": [
        "Bank Credit Analyst",
        "Bank Lending Officer",
        "Book Editor",
        "Branch-Bank Operations Officer",
        "Business Analyst",
        "Foreign Correspondent",
        "Hospital Administrator",
        "Immigration Lawyer",
        "Loan Officer",
        "Newspaper Editor",
    ],
    "LEM": [
        "Architect",
        "Art Director",
        "Building Contractor",
        "City-Planning Engineer",
        "Industrial Engineer",
        "Landscape Architect",
    ],
    "NLE": [
        "Accountant",
        "Bank Credit Analyst",
        "Bank Lending Officer",
        "Certified Public Accountant",
        "City-Planning Engineer",
        "Economist",
        "Financial Analyst",
        "Financial Planner",
        "Industrial Engineer",
        "Loan Officer",
        "Purchasing Manager",
        "Tax Attorney",
    ],
    "ILE": [
        "Advertising Manager",
        "Branch-Bank Operations Officer",
        "Business Consultant",
        "Head Nurse",
        "Immigration Lawyer",
        "Lawyer",
        "Occupational Therapist",
    ],
    "EM": [
        "Apartment/Condominium Supt.",
        "Arcade Attendant",
        "Barber/Stylist",
        "Broadcasting Announcer",
        "Broadcasting/TV Director",
        "Chef",
        "Clothes Designer",
        "Commercial Photographer",
        "Fashion Coordinator",
        "Fashion Designer",
        "Interior Designer",
        "Jeweler",
    ],
    "NEM": [
        "Architect",
        "Architectural Graphic Designer",
        "Building Contractor",
        "Cabinetmaker",
        "City-Planning Engineer",
        "Chief Petroleum Engineer",
        "Landscape Architect",
        "Project Engineer",
    ],
    "IEM": [
        "Advertising Manager",
        "Television Director",
    ],
    "NE": [
        "Advertising Sales Representative",
        "Appraiser",
        "Bank Manager",
        "Caterer",
        "Food-and-Beverage Manager",
        "International Banker",
        "Stockbroker",
        "Tax Attorney",
    ],
    "NIE": [
        "Branch-Bank Operations Officer",
        "Business Agent",
        "Tax Attorney",
    ],
    "IE": [
        "Advertising Account Executive",
        "Advertising Copywriter",
        "Advertising Manager",
        "High-School Principal",
        "Secondary-School Teacher",
        "Wedding Consultant",
    ],
    "C": [
        "Aircraft Inspector",
        "Airline Dispatcher",
        "Airline Lounge Receptionist",
        "Bank Teller",
        "Billing Typist",
        "Blood-Bank Technologist",
        "Customs Inspector",
        "Directory-Assistance Operator",
        "File Clerk",
        "Information Clerk",
        "Legal Assistant",
        "Office Clerk",
        "Postal Clerk",
        "Proofreader",
        "Receptionist",
        "Secretary",
    ],
    "CL": [
        "Agricultural Microbiologist",
        "Bacteriologist",
        "Computer Programmer",
        "Historian",
        "Legal Assistant",
        "Librarian",
        "Microbiologist",
        "Newspaper Columnist",
    ],
    "CLM": [
        "Drafter/Draftsman",
        "Electronics Technician",
        "Laboratory Assistant",
    ],
    "NCL": [
        "Computer Programmer",
        "Economist",
        "Internal Revenue Agent",
        "Laboratory Assistant",
        "Medical Technologist",
        "Pharmacist",
        "Production-Planning Supervisor",
    ],
    "NCI": [
        "Audit Accounting Aide",
        "Tax Attorney",
    ],
    "CIL": [
        "Dietitian",
        "Guidance Counselor",
        "Legal Assistant",
        "Medical Assistant",
        "News Reporter",
    ],
    "CI": [
        "Airline Flight Attendant",
        "Airline-Lounge Receptionist",
        "Medical Assistant",
        "Nurse",
        "Nurse Aide",
        "Police Inspector",
        "Receptionist",
        "Teacher Aide",
    ],
    "CM": [
        "Aircraft Inspector",
        "Animator",
        "Book Designer",
        "Building Inspector",
        "Construction Inspector",
        "Electronics Technician",
        "News Photographer",
    ],
    "NCM": [
        "Construction-Materials Supervisor",
        "Laboratory Assistant",
        "Land Surveyor",
    ],
    "CIM": [
        "Art Teacher",
        "Dental Assistant",
        "Physical Therapist",
    ],
    "NC": [
        "Accounting Clerk",
        "Auditor",
        "Bank Teller",
        "Bookkeeper",
        "Production-Planning Supervisor",
        "Proofreader",
    ],
    "L": [
        "Agricultural Microbiologist",
        "Agronomist",
        "Bacteriologist",
        "Biologist",
        "Botanist",
        "Computer Programmer",
        "Criminologist",
        "Database Manager",
        "Marine Biologist",
        "Microbiologist",
        "Veterinarian",
        "Zoologist",
    ],
    "LM": [
        "Agricultural Engineer",
        "Air-Conditioning Technician",
        "Airline Pilot",
        "Architectural Graphic Designer",
        "Automobile Mechanic",
        "Design Engineer",
        "Diagnostic X-Ray Technologist",
        "Electrician",
        "Film Director",
        "Graphic Designer",
        "Neurosurgeon",
        "Photojournalist",
    ],
    "NLM": [
        "Aeronautical Engineer",
        "Anesthesiologist",
        "Chemical Engineer",
        "Civil Engineer",
        "Computer-Applications Engineer",
        "Design Engineer",
        "Drafter/Draftsman",
        "Electrical Engineer",
        "Electronics Engineer",
        "Geologist",
        "Industrial Engineer",
        "Naval Architect",
        "Mechanical Engineer",
        "Metallurgical Engineer",
        "Mining Engineer",
        "Ophthalmologist",
        "Plastic Surgeon",
        "Seismologist",
    ],
    "ILM": [
        "Cartoonist",
        "Chiropractor",
        "Dentist",
        "Gynecologist",
        "Neurosurgeon",
        "Physical Therapist",
        "Surgeon",
    ],
    "NL": [
        "Biochemist",
        "Chemist",
        "Computer Systems Analyst",
        "Database Manager",
        "Pharmacist",
        "Quality Control Engineer",
        "Systems Analyst",
        "Zoologist",
    ],
    "NIL": [
        "Cardiologist",
        "Cardiovascular Physician",
        "Mathematics Teacher",
        "Pediatrician",
        "Physician",
        "Psychiatrist",
    ],
    "IL": [
        "Animal Technician",
        "Athletic Trainer",
        "Biology Teacher",
        "Cardiologist",
        "Cardiovascular Physician",
        "Child Psychologist",
        "Counseling Psychologist",
        "Dermatologist",
        "Elementary-School Teacher",
        "Guidance Counselor",
        "Gynecologist",
        "Judge",
        "Lawyer",
        "Neurologist",
        "Occupational Therapist",
        "Parole Officer",
        "Pediatrician",
        "Physician",
        "Police Officer",
        "Psychiatrist",
        "Sociologist",
        "Veterinarian",
    ],
    "M": [
        "Air-Conditioning Mechanic",
        "Animator",
        "Artificial-Eye Maker",
        "Art Teacher",
        "Audio Technician",
        "Audiovisual Technician",
        "Automobile Mechanic",
        "Book-Jacket Designer",
        "Cabinetmaker",
        "Construction Electrician",
        "Costume Designer",
        "Diagnostic X-Ray Technologist",
        "Goldsmith",
        "Museum Ceramic Restorer",
        "News Photographer",
    ],
    "NM": [
        "Drafter/Draftsman",
        "Electroplater",
        "Video Operator",
    ],
    "NIM": [
        "Anesthesiologist",
        "dentist",
        "Dialysis",
        "Technician",
    ],
    "IM": [
        "Art Teacher",
        "Cartoonist",
        "Dental Assistant",
        "Dialysis Technician",
    ],
    "N": [
        "Accounting Clerk",
        "Computer-Applications Engineer",
        "Statistician",
    ],
    "NI": [
        "Mathematics Teacher",
        "Tax Attorney",
    ],
    "I": [
        "Elementary-School Teacher",
        "Kindergarten Teacher",
        "Nurse",
        "Nurse Aide",
        "Occupational Therapist",
        "Parole Officer",
        "Second-School Teacher",
    ],
    "CIL": [
        "Dietitian",
        "Guidance Counselor",
        "Legal Assistant",
        "Medical Assistant",
        "News Reporter",
    ],
    "CI": [
        "Airline Flight Attendant",
        "Airline-Lounge Receptionist",
        "Medical Assistant",
        "Nurse",
        "Nurse Aide",
        "Police Inspector",
        "Receptionist",
        "Teacher Aide",
    ],
    "CM": [
        "Aircraft Inspector",
        "Animator",
        "Book Designer",
        "Building Inspector",
        "Construction Inspector",
        "Electronics Technician",
        "News Photographer",
    ],
    "NCM": [
        "Construction Materials Supervisor",
        "Laboratory Assistant",
        "Land Surveyor",
    ],
    "CIM": [
        "Art Teacher",
        "Dental Assistant",
        "Physical Therapist",
    ],
    "NC": [
        "Accounting Clerk",
        "Auditor",
        "Bank Teller",
        "Bookkeeper",
        "Production Planning Supervisor",
        "Proofreader",
    ],
    "L": [
        "Agricultural Microbiologist",
        "Agronomist",
        "Bacteriologist",
        "Biologist",
        "Botanist",
        "Computer Programmer",
        "Criminologist",
        "Database Manager",
        "Marine Biologist",
        "Microbiologist",
        "Veterinarian",
        "Zoologist",
    ],
    "LM": [
        "Agricultural Engineer",
        "Air-Conditioning Technician",
        "Airline Pilot",
        "Architectural Graphic Designer",
        "Automobile Mechanic",
        "Design Engineer",
        "Diagnostic X-Ray Technologist",
        "Electrician",
        "Film Director",
        "Graphic Designer",
        "Neurosurgeon",
        "Photojournalist",
    ],
    "NLM": [
        "Aeronautical Engineer",
        "Anesthesiologist",
        "Chemical Engineer",
        "Civil Engineer",
        "Computer Applications Engineer",
        "Design Engineer",
        "Drafter / Draftsman",
        "Electrical Engineer",
        "Electronics Engineer",
        "Geologist",
        "Industrial Engineer",
        "Naval Architect",
        "Mechanical Engineer",
        "Metallurgical Engineer",
        "Mining Engineer",
        "Ophthalmologist",
        "Plastic Surgeon",
        "Seismologist",
    ],
    "ILM": [
        "Cartoonist",
        "Chiropractor",
        "Dentist",
        "Gynecologist",
        "Neurosurgeon",
        "Physical Therapist",
        "Surgeon",
    ],
    "NL": [
        "Biochemist",
        "Chemist",
        "Computer Systems Analyst",
        "Database Manager",
        "Pharmacist",
        "Quality Control Engineer",
        "Systems Analyst",
        "Zoologist",
    ],
    "NIL": [
        "Cardiologist",
        "Cardiovascular Physician",
        "Mathematics Teacher",
        "Pediatrician",
        "Physician",
        "Psychiatrist",
    ],
    "IL": [
        "Animal Technician",
        "Athletic Trainer",
        "Biology Teacher",
        "Cardiologist",
        "Cardiovascular Physician",
        "Child Psychologist",
        "Counseling Psychologist",
        "Dermatologist",
        "Elementary-School Teacher",
        "Guidance Counselor",
        "Gynecologist",
        "Judge",
        "Lawyer",
        "Neurologist",
        "Occupational Therapist",
        "Parole Officer",
        "Pediatrician",
        "Physician",
        "Police Officer",
        "Psychiatrist",
        "Sociologist",
        "Veterinarian",
    ],
    "M": [
        "Air-Conditioning Mechanic",
        "Animator",
        "Artificial-Eye Maker",
        "Art Teacher",
        "Audio Technician",
        "Audiovisual Technician",
        "Automobile Mechanic",
        "Book Jacket Designer",
        "Cabinetmaker",
        "Construction Electrician",
        "Costume Designer",
        "Diagnostic X-Ray Technologist",
        "Goldsmith",
        "Museum Ceramic Restorer",
        "News Photographer",
    ],
    "NM": [
        "Drafter / Draftsman",
        "Electroplater",
        "Video Operator",
    ],
    "NIM": [
        "Anesthesiologist",
        "Dentist",
        "Dialysis Technician",
    ],
    "IM": [
        "Art Teacher",
        "Cartoonist",
        "Dental Assistant",
        "Dialysis Technician",
    ],
    "N": [
        "Accounting Clerk",
        "Computer Applications Engineer",
        "Statistician",
    ],
    "NI": [
        "Mathematics Teacher",
        "Tax Attorney",
    ],
    "I": [
        "Elementary-School Teacher",
        "Kindergarten Teacher",
        "Nurse",
        "Nurse Aide",
        "Occupational Therapist",
        "Parole Officer",
        "Secondary-School Teacher",
    ],
}

# Backwards-compatibility alias: older modules import STRAND_CAREERS
STRAND_CAREERS = {}