STRAND_CAREERS = {
    "STEM": [
        "Aeronautical Engineer",
        "Anesthesiologist",
        "Architect",
        "Architectural Graphic Designer",
        "Bacteriologist",
        "Biochemist",
        "Biologist",
        "Botanist",
        "Chemical Engineer",
        "Chemist",
        "Chief Petroleum Engineer",
        "Civil Engineer",
        "Computer Programmer",
        "Computer System Analyst",
        "Computer-Applications Engineer",
        "Criminologist",
        "Database Manager",
        "Design Engineer",
        "Diagnostic X-Ray Technologist",
        "Drafter/Draftsman",
        "Electrical Engineer",
        "Electrician",
        "Electronics Engineer",
        "Geologist",
        "Industrial Engineer",
        "Marine Biologist",
        "Mechanical Engineer",
        "Metallurgical Engineer",
        "Microbiologist",
        "Mining Engineer",
        "Naval Architect",
        "Ophthalmologist",
        "Pharmacist",
        "Plastic Surgeon",
        "Quality Control Engineer",
        "Seismologist",
        "Systems Analyst",
        "Veterinarian",
        "Zoologist",
    ],
    "ABM": [
        "Accountant",
        "Accounting Aide",
        "Accounting Clerk",
        "Appraiser",
        "Auditor",
        "Bank Cashier",
        "Bank Credit Analyst",
        "Bank Lending Officer",
        "Bank Manager",
        "Bank Teller",
        "Bookkeeper",
        "Branch-Bank Operations Officer",
        "Business Agent",
        "Business Analyst",
        "Business Consultant",
        "Caterer",
        "Certified Public Accountant",
        "Economist",
        "Executive Secretary",
        "File Clerk",
        "Financial Analyst",
        "Financial Planner",
        "Food-and-Beverage Manager",
        "Foreign Correspondent",
        "Hospital Administrator",
        "Information Clerk",
        "Insurance Agent",
        "Internal Revenue Agent",
        "International Banker",
        "Loan Officer",
        "Office Clerk",
        "Postmaster",
        "Production-Planning Supervisor",
        "Purchasing Manager",
        "Sales Manager",
        "Stockbroker",
        "Tax Attorney",
        "Travel Agent",
        "Wholesaler",
    ],
    "HUMSS": [
        "Agricultural Microbiologist",
        "Agronomist",
        "Art Director",
        "Astronomer",
        "Athletic Trainer",
        "Biology Teacher",
        "Book Editor",
        "Branch-Bank Operations Officer",
        "Child Psychologist",
        "Counseling Psychologist",
        "Dermatologist",
        "Diet Counselor",
        "Dietitian",
        "Elementary-School Teacher",
        "Foreign Correspondent",
        "Guidance Counselor",
        "Gynecologist",
        "Head Nurse",
        "High-School Principal",
        "Historian",
        "Immigration Lawyer",
        "Judge",
        "Kindergarten Teacher",
        "Lawyer",
        "Legal Assistant",
        "Librarian",
        "Mathematics Teacher",
        "Neurologist",
        "Newspaper Columnist",
        "Newspaper Editor",
        "Occupational Therapist",
        "Parole Officer",
        "Pediatrician",
        "Physician",
        "Police Inspector",
        "Police Officer",
        "Psychiatrist",
        "Public Relations Representative",
        "Reception Clerk",
        "Secondary-School Teacher",
        "Sociologist",
        "Teacher Aide",
    ],
    "GAS": [
        "Airline Dispatcher",
        "Airline Lounge Receptionist",
        "Apartment/Condominium Supt.",
        "Arcade Attendant",
        "Blood-Bank Technologist",
        "Broadcasting Announcer",
        "Customs Inspector",
        "Directory-Assistance Operator",
        "Fire Inspector",
        "Hotel Bell captain",
        "Hotel Manager",
        "Jeweler",
        "News Reporter",
        "Pawnbroker",
        "Postal Clerk",
        "Proofreader",
        "Receptionist",
        "Secretary",
        "Warehouse Manager",
    ],
    "ARTS AND DESIGN": [
        "Animator",
        "Art Teacher",
        "Artificial-Eye Maker",
        "Book-Jacket Designer",
        "Book Designer",
        "Building Inspector",
        "Cabinetmaker",
        "Cartoonist",
        "Chef",
        "Clothes Designer",
        "Commercial Photographer",
        "Construction Inspector",
        "Costume Designer",
        "Drafter/Draftsman",
        "Fashion Coordinator",
        "Fashion Designer",
        "Film Director",
        "Goldsmith",
        "Graphic Designer",
        "Interior Designer",
        "Museum Ceramic Restorer",
        "News Photographer",
        "Photojournalist",
        "Television Director",
    ],
    "SPORTS": [],
    "AFA": [
        "Agricultural Engineer",
        "Agricultural Microbiologist",
        "Agronomist",
    ],
    "HE": [
        "Chef",
        "Fashion Coordinator",
        "Fashion Designer",
    ],
    "IA": [
        "Air-Conditioning Mechanic",
        "Air-Conditioning Technician",
        "Airplane Inspector",
        "Airline Pilot",
        "Automobile Mechanic",
        "Building Contractor",
        "Construction Electrician",
        "Electronics Technician",
        "Electroplater",
        "Electrician",
        "Land Surveyor",
        "Video Operator",
    ],
    "ICT": [
        "Audio Technician",
        "Audiovisual Technician",
        "Broadcasting/TV Director",
        "Commercial Photographer",
        "Computer Programmer",
        "Database Manager",
        "Electronics Technician",
    ],
}
